### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by abgoldstein** [dabit/banjo#1]
Great lightning talk at RailsConf! I was trying to get this working on my machine but can't seem to get any output. Everything bundles correctly and I see this output from `unimidi list`:

```
input:
0) Apple Inc. IAC Driver
output:
1) Apple Inc. IAC Driver
```

but I can't seem to get any audio. Do I have to do anything more specific with GarageBand besides just have it running in the background?

**Comment by dabit** [comment]
I just pushed a Garage band file to be included with the sample/basic. Open it before running the script to see what happens.

One of the problems that I ran into helping other people at Railsconf was that they were not running the sample from its folder. 

So cd into the folder first.

```
cd sample/basic
bundle
ruby song.rb
```

**Comment by abgoldstein** [comment]
Thanks, David! It was just me having no idea what I'm doing it GarageBand. Everything seems to be working now. I'll definitely play with this more this week. Thanks for putting it out there!

**Comment by dabit** [comment]
Cool!
