### ISSUE TITLE
Not hearing any sound on OSX10.10.4 

### ISSUE THREAD

**Issue by marplx** [dabit/banjo#11]
Hi,
i followed your description step by step. Running the basic example with `ruby song.rb` after `bundle install` I can see the console output but hear no sound.
The midi channels seem to be correctly configured:

```
$ unimidi list
input:
0) Apple Inc. IAC Driver
2) Apple Inc. IAC Driver
4) Apple Inc. IAC Driver
6) Apple Inc. IAC Driver
output:
1) Apple Inc. IAC Driver
3) Apple Inc. IAC Driver
5) Apple Inc. IAC Driver
7) Apple Inc. IAC Driver
```

I use the following ruby version:
`ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`

What am I doing wrong?

**Comment by marplx** [comment]
Do I need Garageband?

**Comment by dabit** [comment]
Hi,

Yes, you need to have GarageBand opened and create a software instrument track on it. Then you should start hearing the sounds.

**Comment by marplx** [comment]
Works! Thanks!

**Comment by marfnk** [comment]
But with GarageBand I can only use one track?
I tried to add more than one software instrument tracks but all channels from the "/nickel" project played on the last created track.
How to support multi-channel sounds?
