### ISSUE TITLE
Unable to run "ruby sample/song.rb"

### ISSUE THREAD

**Issue by benWoz** [dabit/banjo#3]
I'm running Ruby 2.1.2 on a current Mac and have installed the gem using a Gemfile. When I try to run "ruby song.rb" I get: 
... "banjo/sample/basic/channels/main_channel.rb:17:in `perform': undefined method`tick_note' for #MainChannel:0x007f8ecb910508 (NoMethodError)"

**Comment by dabit** [comment]
Hey Ben,

This was fixed with c0f9d1fbd292b0e629607ca6c8421fc45d6700c1 .

If you pull the latest version of the repo it should be fixed.

**Comment by dabit** [comment]
Meant commit c0f9d1fbd292b0e629607ca6c8421fc45d6700c1
